server:
  port: 8060

spring:
  application:
    name: deliverys

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/delivery-service
      database: delivery-service
      username: <your-mongo-username>
      password: <your-mongo-password>

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
